// <auto-generated />
using System;
using Airline;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airline.Data.Migrations
{
    [DbContext(typeof(AirlineDbContext))]
    [Migration("20250926165801_One-To-Many relationship mapping")]
    partial class OneToManyrelationshipmapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Airline.Enities.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Airline.Enities.AircraftRoute", b =>
                {
                    b.Property<int>("AircraftId")
                        .HasColumnType("int")
                        .HasColumnName("AC_Id");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("Route_Id");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("int")
                        .HasColumnName("Num_Pf_Pass");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AircraftId", "RouteId", "Departure");

                    b.ToTable("Aircraft_Routes");
                });

            modelBuilder.Entity("Airline.Enities.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cont_person");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Airline.Enities.AirlinePhones", b =>
                {
                    b.Property<int>("AirlineId")
                        .HasColumnType("int")
                        .HasColumnName("AL_Id");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("AirlineId", "Phone");

                    b.ToTable("Airline_Phones");
                });

            modelBuilder.Entity("Airline.Enities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int?>("BirthDayDay")
                        .HasColumnType("int")
                        .HasColumnName("BD_Day");

                    b.Property<int?>("BirthDayMonth")
                        .HasColumnType("int")
                        .HasColumnName("BD_Month");

                    b.Property<int?>("BirthDayYear")
                        .HasColumnType("int")
                        .HasColumnName("BD_Year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Airline.Enities.EmployeeQualifications", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Emp_Id");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmployeeId", "Qualification");

                    b.ToTable("Emp_Qualifications");
                });

            modelBuilder.Entity("Airline.Enities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Distance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Airline.Enities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Airline.Enities.Aircraft", b =>
                {
                    b.HasOne("Airline.Enities.Airline", "Airline")
                        .WithMany("Aircrafts")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Airline.Enities.Crew", "Crew", b1 =>
                        {
                            b1.Property<int>("AircraftId")
                                .HasColumnType("int");

                            b1.Property<string>("AssistantPilot")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Host1")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Host2")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MajorPilot")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AircraftId");

                            b1.ToTable("Aircrafts");

                            b1.WithOwner()
                                .HasForeignKey("AircraftId");
                        });

                    b.Navigation("Airline");

                    b.Navigation("Crew")
                        .IsRequired();
                });

            modelBuilder.Entity("Airline.Enities.AirlinePhones", b =>
                {
                    b.HasOne("Airline.Enities.Airline", null)
                        .WithMany("Phones")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Airline.Enities.Employee", b =>
                {
                    b.HasOne("Airline.Enities.Airline", "Airline")
                        .WithMany("Employees")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Airline.Enities.EmployeeQualifications", b =>
                {
                    b.HasOne("Airline.Enities.Employee", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Airline.Enities.Transaction", b =>
                {
                    b.HasOne("Airline.Enities.Airline", "Airline")
                        .WithMany("Transactions")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Airline.Enities.Airline", b =>
                {
                    b.Navigation("Aircrafts");

                    b.Navigation("Employees");

                    b.Navigation("Phones");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Airline.Enities.Employee", b =>
                {
                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
